better batch pipeline

diff --git a/bin/discord_bot b/bin/discord_bot
--- a/bin/discord_bot
+++ b/bin/discord_bot
@@ -1,29 +1,18 @@
 #!/usr/bin/bash
 
-PROJECT="."
-
-if [ -d "$1" ]; then
-    PROJECT="$1"
-fi
+PROJECT="$(dirname $0)/.."
 
 CONFIG=$PROJECT/config
 SRC=$PROJECT/src
 
-if [ ! -d "$CONFIG" ]; then
-    echo "Could not find config directory." >&2
-    exit 1
-fi
-
-if [ ! -d "$SRC" ]; then
-    echo "Could not find src directory." >&2
-    exit 1
-fi
+[ -d "$CONFIG" ] || (echo "Could not find config directory." >&2 && exit 1)
+[ -d "$SRC" ]    || (echo "Could not find src directory." >&2    && exit 1)
 
 while :; do
     python3 -- "$SRC/chatbot/DiscordBot.py" \
         "$CONFIG/discord_config.json" \
         "$CONFIG/discord_token.txt"
 
-    [ ! "$?" -eq 69 ] && break
+    [ "$?" -eq 69 ] || break
 done
 
diff --git a/bin/metacentrum_batch_discord_bot b/bin/metacentrum_batch_discord_bot
--- a/bin/metacentrum_batch_discord_bot
+++ b/bin/metacentrum_batch_discord_bot
@@ -19,15 +19,14 @@ if [ ! -d $SCRATCH_VENV ]; then
     mkdir -p $SCRATCH_VENV
     python3.10 -m venv $SCRATCH_VENV
     source $SCRATCH_VENV/bin/activate
-    pip3 install discord.py torch transformers
+
+    pip3 install discord.py transformers torch ||
+        (echo "Installing dependencies failed." >&2 && exit 1)
 else
     source $SCRATCH_VENV/bin/activate
 fi
 
-CONFIG=$PROJECT/discord_config.json
-TOKEN=$PROJECT/discord_token.txt
+$PROJECT/bin/discord_bot
 
-python3 -- $PROJECT/src/chatbot/DiscordBot.py $CONFIG $TOKEN
-
-rm -rf $SCRATCHDIR/*
+#rm -rf $SCRATCHDIR/*
 
